apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "deployments"
    verbs:
      - "create"
      - "delete"
      - "list"